apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: portfolio-files
  files:
  - index.html
  - css/style.css

generatorOptions:
  disableNameSuffixHash: true

resources:
- portfolio-deployment.yaml
